-- MySQL Script generated by MySQL Workbench
-- 10/28/15 14:18:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


---------------------------------
-- Table '824Sim'.'Nodes'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Nodes (
  'NodeId' INT NOT NULL,
  PRIMARY KEY ('NodeId'));

-- -----------------------------------------------------
-- Table '824Sim'.'FaultMessages'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FaultMessages (
  'MESSAGENUM' INTEGER PRIMARY KEY AUTOINCREMENT,
  'NODEID' INT UNSIGNED NOT NULL ,
  'PARAM2' TINYINT(1) NULL ,
  'PARAM3' TINYINT(1) NULL ,
  'PARAM4' TINYINT(1) NULL ,
  'PARAM5' TINYINT(1) NULL );
